CXXFLAGS =	 -g3 -Wall -fmessage-length=0

OBJS =		i160033_cp_assignment3.o String.o

LIBS =

TARGET =	i160033_cp_assignment3

$(TARGET):	$(OBJS)
	$(CXX) -o $(TARGET) $(OBJS) $(LIBS)

all:	$(TARGET)

clean:
	rm -f $(OBJS) $(TARGET)
