CXXFLAGS =	-O2 -g -Wall -fmessage-length=0

OBJS =		i160033_cp_assignment4.o String.o

LIBS =

TARGET =	i160033_cp_assignment4.exe

$(TARGET):	$(OBJS)
	$(CXX) -o $(TARGET) $(OBJS) $(LIBS)

all:	$(TARGET)

clean:
	rm -f $(OBJS) $(TARGET)
